spring:
  thymeleaf:
    cache: false
    enabled: true
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html

  resources:
    static-locations: classpath:/static/
    add-mappings: true
    cache-period: 3600
    chain:
      cache: true
      enabled: true
      gzipped: true
      html-application-cache: true

  datasource:
      # druid
      url: jdbc:mysql://localhost:3306/miaosha?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 1000
      initialSize: 100
      maxWait: 60000
      minIdle: 500
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
redis:
    host: 127.0.0.1
    port: 6379
    max-idle: 500
    max-total: 1000
    max-wait-millis: 3000
mybatis:
  type-aliases-package: com.swg.miaosha.model
  mapper-locations: classpath:com/njupt/dao/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
