spring:
  thymeleaf:
    cache: false
    enabled: true
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html

  datasource:
      # druid
      url: jdbc:mysql://localhost:3306/miaosha?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
redis:
  host: 127.0.0.1
  port: 6379
  timeout: 3
  max-idle: 10
  max-total: 10
  max-wait-millis: 3000
mybatis:
  type-aliases-package: com.swg.miaosha.model
  mapper-locations: classpath:com/njupt/dao/mapper/**.xml
